AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnvName:
    Description: Environment name tag
    Type: String
    Default: secretdemo

Resources:
  SecretPsqlRootPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: psqlrootpassword
      Description: "PAQL root dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"+ - = . _ : / @.'
      Tags:
        -
          Key: Name
          Value: !Sub ${EnvName}-psql-secret