AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnvName:
    Description: Environment name tag
    Type: String
    Default: secretdemo

Resources:
  SecretPsqlRootPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: psqlrootpassword02
      Description: "PAQL root dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        PasswordLength: 24
        ExcludePunctuation: True
      Tags:
        -
          Key: Name
          Value: !Sub ${EnvName}-psql-secret